spring.application.name=scores

# Exposer les métriques de base et Prometheus via Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
